name: CI pipeline

on: ['push']

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Launch docker-compose stack
        run: docker compose -f compose.test.yml up -d --build
        env:
          JIRA_HOST: ${{ secrets.JIRA_HOST }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Run simple integration tests
        run: ./tests/integration/run-integration-tests.sh

  check-npm-tasks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Check if ESLint passes
        if: '!cancelled()'
        run: npm run lint-check

      - name: Check if Prettier passes
        if: '!cancelled()'
        run: npm run format-check

      - name: Check if the code transpiles
        if: '!cancelled()'
        run: npm run transpile-check

      - name: Check if the unit tests pass
        if: '!cancelled()'
        run: npm run test
